server:
  port: 9191

logging:
  level:
    root: INFO
    com.fionapet.tenant: INFO
  config: classpath:logback-boot.xml

spring:
  application:
    name: fiona-tenant
  datasource:
    url: jdbc:mysql://localhost:3306/core_new?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # disable jdbc metadata (avoid the exception: PgConnection.createClob() is not yet implemented)
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.multiTenancy: DATABASE
      hibernate.tenant_identifier_resolver: com.fionapet.tenant.multitenant.MultiTenantSchemaResolver
      hibernate.multi_tenant_connection_provider: com.fionapet.tenant.multitenant.MultiTenantSchemaProvider
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-core.xml
    default-schema: core_new
  cache:
    jcache:
      config: classpath:ehcache.xml

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: "*"

app:
  security:
    authentication:
      jwt:
        # https://www.base64encode.org/
        secret-key: ZGVtbw== 
        expiration-in-seconds: 86400 

  tenant:
    context:
      default:
        schema: core_new
